//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int FacilityId { get; set; }
        public string FacilityName { get; set; }
        public Nullable<int> PharmacyId { get; set; }
    
        public virtual Pharmacy Pharmacy { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
